title:             Dive Into Analytics Blog
email:             hareeshbahuleyan@gmail.com
description:       Personal Website and Data Analytics Blog
author:            Hareesh Bahuleyan
baseurl:           "/blog"
url:               "https://hareeshbahuleyan.github.io"

# Social Profiles
twitter_username: HareeshHPB
github_username:  HareeshBahuleyan
facebook_username:  hareesh.bahuleyan

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
#  - jekyll-sitemap
#  - jekyll-seo-tag
